import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.metrics import explained_variance_score, mean_absolute_error, mean_squared_error, r2_score
from sklearn.datasets import make_regression

#function for regression evaluation:
def regression_results(y_true, y_pred, regr_type):
    # Regression metrics
    ev = explained_variance_score(y_true, y_pred)
    mae = mean_absolute_error(y_true, y_pred)
    mse = mean_squared_error(y_true, y_pred)
    r2 = r2_score(y_true, y_pred)

    print('Evaluation metrics for ' + regr_type + ' Linear Regression')
    print('explained_variance: ', round(ev, 4))
    print('r2: ', round(r2, 4))
    print('MAE: ', round(mae, 4))
    print('MSE: ', round(mse, 4))
    print('RMSE: ', round(np.sqrt(mse), 4))
    print()



#generationg data
"""
The output of make_regression is generated by applying a random linear regression model based on n_informative nonzero
regressors and some adjustable gaussian noise
Along with the features and the target vairable,
the regression model coefficients can also be obtained from the output.
"""

X, y, ideal_coef = make_regression(n_samples=100, n_features=100, n_informative=10, noise=10, random_state=42, coef=True)

# Get the ideal predictions based on the informative coefficients used in the regression model
ideal_predictions = X @ ideal_coef

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test, ideal_train, ideal_test = train_test_split(X, y, ideal_predictions, test_size=0.3, random_state=42)

#Initialize and fit the linear regression models and use them to predict the target
lasso = Lasso(alpha=0.1)
ridge = Ridge(alpha=1.0)
linear = LinearRegression()

# Fit the models
lasso.fit(X_train, y_train)
ridge.fit(X_train, y_train)
linear.fit(X_train, y_train)

# Predict on the test set
y_pred_linear = linear.predict(X_test)
y_pred_ridge = ridge.predict(X_test)
y_pred_lasso = lasso.predict(X_test)


regression_results(y_test, y_pred_linear, 'Ordinary')
regression_results(y_test, y_pred_ridge, 'Ridge')
regression_results(y_test, y_pred_lasso, 'Lasso')


#ploting a results vs actual data
fig, axes = plt.subplots(2, 3, figsize=(18, 10), sharey=True)

axes[0, 0].scatter(y_test, y_pred_linear, color="red", label="Linear")
axes[0, 0].plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'k--')
axes[0, 0].set_title("Linear Regression")
axes[0, 0].set_xlabel("Actual", )
axes[0, 0].set_ylabel("Predicted", )

axes[0, 2].scatter(y_test, y_pred_lasso, color="blue", label="Lasso")
axes[0, 2].plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'k--')
axes[0, 2].set_title("Lasso Regression", )
axes[0, 2].set_xlabel("Actual", )

axes[0, 1].scatter(y_test, y_pred_ridge, color="green", label="Ridge")
axes[0, 1].plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'k--')
axes[0, 1].set_title("Ridge Regression", )
axes[0, 1].set_xlabel("Actual", )

axes[0, 2].scatter(y_test, y_pred_lasso, color="orange", label="Lasso")
axes[0, 2].plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'k--')
axes[0, 2].set_title("Lasso Regression", )
axes[0, 2].set_xlabel("Actual", )

# Line plots for predictions compared to actual and ideal predictions
axes[1, 0].plot(y_test, label="Actual", lw=2)
axes[1, 0].plot(y_pred_linear, '--', lw=2, color='red', label="Linear")
axes[1, 0].set_title("Linear vs Ideal", )
axes[1, 0].legend()

axes[1, 1].plot(y_test, label="Actual", lw=2)
# axes[1,1].plot(ideal_test, '--', label="Ideal", lw=2, color="purple")
axes[1, 1].plot(y_pred_ridge, '--', lw=2, color='green', label="Ridge")
axes[1, 1].set_title("Ridge vs Ideal", )
axes[1, 1].legend()

axes[1, 2].plot(y_test, label="Actual", lw=2)
axes[1, 2].plot(y_pred_lasso, '--', lw=2, color='orange', label="Lasso")
axes[1, 2].set_title("Lasso vs Ideal", )
axes[1, 2].legend()

plt.tight_layout()
plt.show()


#checing a coefficients for each model (actual data to linia pozioma wzdłuż y =0):

# Model coefficients
linear_coeff = linear.coef_
ridge_coeff = ridge.coef_
lasso_coeff = lasso.coef_


# Plot the coefficients
x_axis = np.arange(len(linear_coeff))
x_labels = np.arange(min(x_axis),max(x_axis),10)
plt.figure(figsize=(12, 6))

plt.scatter(x_axis, ideal_coef,  label='Ideal', color='black', ec='k', alpha=0.4)
plt.bar(x_axis - 0.25, linear_coeff, width=0.25, label='Linear Regression', color='blue')
plt.bar(x_axis, ridge_coeff, width=0.25, label='Ridge Regression', color='green')
plt.bar(x_axis + 0.25, lasso_coeff, width=0.25, label='Lasso Regression', color='red')

plt.xlabel('Feature Index')
plt.ylabel('Coefficient Value')
plt.title('Comparison of Model Coefficients')
plt.xticks(x_labels)
plt.legend()
plt.show()


# Plot the coefficient residuals
x_axis = np.arange(len(linear_coeff))

plt.figure(figsize=(12, 6))

plt.bar(x_axis - 0.25, ideal_coef - linear_coeff, width=0.25, label='Linear Regression', color='blue')
plt.bar(x_axis, ideal_coef - ridge_coeff, width=0.25, label='Ridge Regression', color='green')
# plt.bar(x_axis + 0.25, ideal_coef - lasso_coeff, width=0.25, label='Lasso Regression', color='red')
plt.plot(x_axis, ideal_coef - lasso_coeff, label='Lasso Regression', color='red')

plt.xlabel('Feature Index')
plt.ylabel('Coefficient Value')
plt.title('Comparison of Model Coefficient Residuals')
plt.xticks(x_labels)
plt.legend()
plt.show()

"""
lasso coefs wyszły prawie tak samo jak idealne coefs. bardzo dobra predykcja
"""


#teraz sprawdzimy najlepszy parametr do predykcyj przy użyciu regresji lasso:

#Part 1. Choose a threshold value to select features based on the Lasso model coefficients


threshold = 5 # selected by inspection of residuals plot

# Create a dataframe containing the Lasso model and ideal coefficients
feature_importance_df = pd.DataFrame({
    'Lasso Coefficient': lasso_coeff,
    'Ideal Coefficient': ideal_coef
})

# Mark the selected features
feature_importance_df['Feature Selected'] = feature_importance_df['Lasso Coefficient'].abs() > threshold


print("Features Identified as Important by Lasso:")
print(feature_importance_df[feature_importance_df['Feature Selected']])

print("\nNonzero Ideal Coefficient Indices")
print(feature_importance_df[feature_importance_df['Ideal Coefficient']>0])


# 9 z 10 ważnych parametrów zostalo użytych do predykcji


#Part 2. Use the threshold to select the most important features for use in modelling

important_features = feature_importance_df[feature_importance_df['Feature Selected']].index

# Filter features
X_filtered = X[:, important_features]
print("Shape of the filtered feature set:", X_filtered.shape)

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test, ideal_train, ideal_test = train_test_split(X_filtered, y, ideal_predictions, test_size=0.3, random_state=42)


#Part 3. Fit and apply the three models to the selected features
# Initialize the models
lasso = Lasso(alpha=0.1)
ridge = Ridge(alpha=1.0)
linear = LinearRegression()

# Fit the models
lasso.fit(X_train, y_train)
ridge.fit(X_train, y_train)
linear.fit(X_train, y_train)

# Predict on the test set
y_pred_linear = linear.predict(X_test)
y_pred_ridge = ridge.predict(X_test)
y_pred_lasso = lasso.predict(X_test)

#  Print the regression performance results
print(regression_results(y_test, y_pred_linear, 'Linear Regression'))
print(regression_results(y_test, y_pred_ridge, 'Ridge'))
print(regression_results(y_test, y_pred_lasso, 'Lasso'))


#PODSUMOWANIE:  wszystkie wyniki się znacznie poprawiły szczególnie dla zwykłej regresji liniowej i ridge, r2 z wartości poniżem 0.5 w obu przypadkach
# wzrosła do 0.99. ozacza to że prawie wszystko udało się idealnie przewidzieć








